[package]
name = "ezp-log-to-csv"
version = "0.1.1"
authors = ["Chrysanthemum Lovelace <chrysanthemum@pitt.edu>"]
edition = "2021"

[dependencies]
anyhow = "1.0.51"
csv = "1.1.6"
structopt = "0.3.25"

[features]
backtrace = ["anyhow/backtrace"]
